#!/bin/bash 
# auxiliar do limitador.
# Autor: @Fs0usa
# Data de criação: 01/04/17
# Objetivo: Limitar o numero de conexoes simultaneas
# Descrição: Limita usando o cron, logo não eh porssivel ter 100 de precisão
# Projeto: Fechado
# Utiluze por sua conta e risco, não modifique o script com o intuito
# de ganhar em cima de tal.

# Tabelas de cores que eu utilizo.
fim="tput sgr0"
bold="tput bold"
ciano="\e[1;36m"
branco="\e[1;37m"
vermelho="\e[1;31m" 
amarelo="\e[1;33m"
azul="\e[1;34m"
verde="\e[1;32m"
limpa="tput setaf 9"
# Inicio do script

# Função parar verificar existe.
verifique() {
awk -F ":" '{print $1}' /etc/passwd > /bin/logs.pack/users.txt

    if grep -Fxq $usuario /bin/logs.pack/users.txt
    then
    tput setaf 7 ; tput bold
    else
    echo -e "$vermelho
O usuário $usuario não  existe,  por favor digite um usuário que exista a seguir."; $fim; tput setaf 7; tput bold
    read -p ":: "  usuario
    fi
		if grep -Fxq $usuario /bin/logs.pack/users.txt
        then
        tput setaf 7 ; tput bold
        else
        clear
        echo -e "$vermelho
Você  digitou um nome de usuário não existente duas vezes."; $fim; tput setaf 7; tput bold
		exit   
        fi
}

verifique2() {
VERIFICAR=`grep -s -c "$usuario" /bin/logs.pack/usuarios.pack.db`
if [[ $VERIFICAR = 1 ]]; then	
	sed -i "/$usuario/d" /bin/logs.pack/usuarios.pack.db	
fi
}

verifique3() {
if (echo "$limite" | egrep "[^0-9]" 2> /dev/null)
then
clear
echo -e "$vermelho Número inválido"; $fim
exit
fi
}
clear
#hostname da maquina
nonename=`uname -n`
$bold
echo -e "$verde
Bem vindo(a) $nonename."; $fim

# var. usuários existentes.
users_existentes=`awk -F":" '{if($3>=1000 ) print $1}' /etc/passwd | grep -v "nobody"`
# tabela com os.usiarios existentes
echo -e "$amarelo
Usuário(s) existente(s):
$ciano
$users_existentes
"; $fim
# interação com o usuário        
tput setaf 7 ; tput bold
read -p "[Digite o usuário que deseja limitar]: " usuario
verifique
usuario="$usuario:"
verifique2
read -p "[Qual o n° de conexoes simultâneas permitidas?]: " limite
verifique3
read -p "[Qual tipo de limite? ( 1=Deleta 2=Queima_PID )]: " tipo_do_limite
$fim

case $tipo_do_limite in
1)
clear
echo $usuario$limite:$tipo_do_limite >> /bin/logs.pack/usuarios.pack.db
echo -e "$verde Concluido, o limite foi associado." ; $fim ;;
2)
clear
echo $usuario$limite:$tipo_do_limite >> /bin/logs.pack/usuarios.pack.db
echo -e "$verde Concluido, o limite foi associado." ; $fim ;;
*)
clear
echo "$vermelho Responda apenas 1 ou 2"
$fim ;;
esac